### ISSUE TITLE
Package is being built in development environment

### ISSUE THREAD

**Issue by mdedys** [lightninglabs/lnc-web#52]
Hey folks, I am experimenting with lnc-web and ran into eval() issues with a web extension. I was running WASM in the wrong script but noticed this package isn't being built in production mode.

```
mode: process.env.NODE_ENV === 'production' ? 'production' : 'development',
```

This makes sense but you are not setting NODE_ENV anywhere in the CI pipeline which results in the mode being set to `development`. This mode results in the following: https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/config/defaults.js#L155

devtool running in `eval` mode is not ideal and it is not recommended for production to use `false`. (https://webpack.js.org/configuration/devtool/#devtool)

Solution:
Change `"prepare": "npm run build"` --> `"prepare": "NODE_ENV=production npm run build",` 

Can submit a PR unless I am missing something.

**Comment by kaloudis** [comment]
Great catch. I think we had `react-scripts` handling the build process originally, which handled setting the `NODE_ENV`.

Please submit a PR, but instead of putting it on the the `prepare` script, please prefix it on the `build` script.

IE.
Change `"build": "webpack"` -->`"build": "NODE_ENV=production webpack"`

Thank you.
