### ISSUE TITLE
TypeScript types package?

### ISSUE THREAD

**Issue by secondl1ght** [lightninglabs/lnc-web#87]
Hello,

Is there a TS types package that can be used to import LNC types into files?

Thanks

**Comment by jamaljsr** [comment]
The TS types are included in the `lnc-web` package so there is no need for a separate `@types` package.

**Comment by secondl1ght** [comment]
Ah ok I tried importing some types like `Feature` for example and it wasn't working, it looks like there is only a default `LNC` type exported but maybe I can derive all the types from the single root type.

**Comment by jamaljsr** [comment]
All of the protobuf types are re-exported in `lnc-web` from the `lnc-core` package. You can see them all listed [here](https://github.com/lightninglabs/lnc-core/blob/main/lib/types/proto/index.ts). They are nested under an export named after the gRPC package (ex: `lnrpc`, `routerrpc`, etc). We do this because some type names from one package conflict with names from other packages, they aren't globally unique, so they can't all be exported from the package root level.

To use the `Feature` type, you would need to do the following:
```ts
import { lnrpc } from '@lightninglabs/lnc-web';

function createFeature(): lnrpc.Feature {
  const feature: lnrpc.Feature = {
    name: 'test-feature',
    isRequired: false,
    isKnown: true,
  };

  return feature;
}
```

**Comment by secondl1ght** [comment]
Ah great, thank you for the information!

**Comment by jamaljsr** [comment]
Cool. I'm going to close this issue now, but feel free to comment if you have any more questions about this.
